### ISSUE TITLE
Cant run Jekyll 4.0 return error =>`find_directory_manifest': wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by reatlat** [envygeeks/jekyll-assets#622]
- [x] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [x] I Am on Linux
  - [x] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [x] Debian
- [ ] I am on macOS 10.13
- [ ] I am on macOS 10.14
- [x] I am on macOS 10.15
- [x] I'm on Docker
  - [x] I understand Docker may be unsupported

## Description

I run clean Jekyll 4.0 with assets and can't do it for reason in this file
 [/usr/local/bundle/gems/jekyll-assets-3.0.12/lib/jekyll/assets/manifest.rb:58](https://github.com/envygeeks/jekyll-assets/blob/ce5c8cc43df9911e0788f06423a27375ee67c00f/lib/jekyll/assets/manifest.rb#L46):in `find_directory_manifest': wrong number of arguments (given 2, expected 1) (ArgumentError)

Is it my local issue, or new Jekyl not supported?

**Comment by rgant** [comment]
I believe this is actually an issue with a change in sprockets 4.0.0:

```
ArgumentError: wrong number of arguments (given 2, expected 1)
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets/manifest.rb:58:in `find_directory_manifest'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-4.0.0/lib/sprockets/manifest.rb:56:in `initialize'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets/manifest.rb:29:in `initialize'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets/env.rb:48:in `new'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets/env.rb:48:in `initialize'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets.rb:24:in `new'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-assets-3.0.12/lib/jekyll/assets.rb:24:in `block in <top (required)>'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/hooks.rb:103:in `block in trigger'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/hooks.rb:102:in `each'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/hooks.rb:102:in `trigger'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:166:in `read'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/commands/doctor.rb:25:in `process'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/commands/doctor.rb:17:in `block (2 levels) in init_with_program'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/rgant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/exe/jekyll:15:in `<top (required)>'
  /Users/rgant/.rbenv/versions/2.6.5/bin/jekyll:23:in `load'
  /Users/rgant/.rbenv/versions/2.6.5/bin/jekyll:23:in `<top (required)>'
```

**Comment by rgant** [comment]
Probably a duplicate of #589

**Comment by rgant** [comment]
Fixed this by forcing the earlier version:

```
gem "sprockets", "~> 3.7"
```

**Comment by envygeeks** [comment]
This is issue is fixed and landed in master last night.

**Comment by dessita** [comment]
I'm still experiencing this issue when I update sprockets from 3.7 to 4.0

**Comment by Philzen** [comment]
Trying to use jekyll-assets with jekyll 4.x and running into this problem (also took me a while to find out all tags but `{% asset %}` are gone, as all documentation on the web seems outdated and i couldn't find anything recent). 

Current master doesn't allow to downgrade sprockets, so i'm stuck here :(

**Comment by acgourley** [comment]
@Philzen just did the same thing as you it seems. Did you ever find a solution?
